platform:
  - x64
configuration:
  - Release
environment:
  QTDIR: C:\Qt\5.7\msvc2015_64
before_build:
  - mkdir c:\projects\core-build
  - cd c:\projects\core-build
  - cmake ../core -G "Visual Studio 14 2015 Win64"
  - dir
